import type { Metadata } from "next";
// Using Geist fonts via next/font/google can fail under Turbopack in some
// environments due to internal module resolution issues. We fallback to a
// reliable Google font pair (Inter + Fira Code) keeping CSS variables so the
// rest of the app does not break. If you want Geist specifically, download
// the WOFF2 files and switch to next/font/local.
import { Inter, Fira_Code } from "next/font/google";
import "./globals.css";

const geistSans = Inter({
  variable: "--font-geist-sans",
  subsets: ["latin"],
  display: "swap",
});

const geistMono = Fira_Code({
  variable: "--font-geist-mono",
  subsets: ["latin"],
  display: "swap",
});

export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="en">
      <body
        className={`${geistSans.variable} ${geistMono.variable} antialiased`}
      >
        {children}
      </body>
    </html>
  );
}
